server:
  port: 8080

logging:
  level:
    org.springframework.cloud.gateway: ERROR
    org.springframework.http.server.reactive: ERROR
    org.springframework.web.reactive: ERROR
    reactor.ipc.netty: ERROR
    reactor.netty: ERROR

services:
  medico: http://localhost:8081
  usuarios: http://localhost:8082